sudo: required

services:
  - docker

env:
  matrix:
    - CI_ROS_DISTRO="dashing"

install:
  - docker build -t convex_decomposition_$CI_ROS_DISTRO -f Dockerfile-$CI_ROS_DISTRO .

script:
  - docker run convex_decomposition_$CI_ROS_DISTRO /bin/bash -c "source install/setup.bash && colcon test && colcon test-result"
