FROM ros:dashing-ros-core

RUN apt-get update && apt-get install -y \
    build-essential clang-format python3-colcon-common-extensions

# Create ROS workspace
COPY . /ws/src/convex_decomposition
WORKDIR /ws

# Use rosdep to install all dependencies (including ROS itself)
RUN rosdep install --from-paths src -i -y --rosdistro dashing

RUN /bin/bash -c "source /opt/ros/dashing/setup.bash && \
    colcon build --parallel-workers 1 && \
    colcon test --parallel-workers 1"
